In [1]:
import pandas as pd
import numpy as np

## Finding Matches

In [2]:
data = {
    'name': ['Alice', 'Bob', 'Carol', 'David', 'Emma'],
    'city': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Gothenburg'],
    'age': [34, 28, 45, 31, 26]
}

df = pd.DataFrame(data)
print(df)

    name        city  age
0  Alice   Stockholm   34
1    Bob  Gothenburg   28
2  Carol       Malmö   45
3  David     Uppsala   31
4   Emma  Gothenburg   26


In [3]:
match = df[df["city"]=="Gothenburg"]
if match.empty:
    print("no match found")
else:
    for i in match.index:
        matches = match.index.tolist()
    print(f"Matching Indexes: {matches}")

Matching Indexes: [1, 4]


In [4]:
match = df[df["name"]== "Zara"]
if match.empty:
    print ("No match found")
else:
    matches = match.index.tolist()  
    print(f"Matches found: {matches}")

No match found


## Sorting

In [5]:
scores = np.array([0.3, 0.8, 0.1, 0.9, 0.5])
sorted_indices = np.argsort(scores)
print(sorted_indices)

[2 0 4 1 3]


### invert the sorting

In [6]:
sorted_indices = np.argsort(scores)[::-1]
print(sorted_indices)

[3 1 4 0 2]


### Limit the output

In [7]:
sorted_indices = np.argsort(scores)[::-1][:3] #From 0 to 3 - 3 not included
print(sorted_indices)

[3 1 4]


## Exercises

In [8]:
#print indexes for values sorted from low to high
scores = np.array([0.6, 0.2, 0.9, 0.4, 0.7, 0.1])
sorted_scores = np.argsort(scores)
print(sorted_scores)

[5 1 3 0 4 2]


In [9]:
#print indexes for values sorted from high to low
sorted_scores = np.argsort(scores)[::-1]
print(sorted_scores)

[2 4 0 3 1 5]


In [10]:
#print indexes for highest 2 values
sorted_scores = np.argsort(scores)[::-1][:2]
print(sorted_scores)

[2 4]


In [11]:
#print 3 lowest values
scores2 = np.array([0.55, 0.12, 0.88, 0.34, 0.76, 0.91, 0.23])
sorted_btm3 = np.argsort(scores2)[:3]
print(sorted_btm3)

[1 6 3]


# Combined matching and sorting

In [12]:
data2 = {
    'name': ['Alice', 'Bob', 'Carol', 'David', 'Emma'],
    'score': [0.3, 0.8, 0.1, 0.9, 0.5]
}

df2 = pd.DataFrame(data2)
print(df2)

    name  score
0  Alice    0.3
1    Bob    0.8
2  Carol    0.1
3  David    0.9
4   Emma    0.5


In [13]:
match =df2[df2["name"]=="Carol"]
if match.empty:
    print("No match found")
else:
    matches = match.index.tolist()
print(f"Matches found: {matches}")
print(f"Carol's score = {df2["score"][matches].values[0]}")


Matches found: [2]
Carol's score = 0.1


In [14]:
# Getting a value by index position
df2['score'].iloc[2]      # by position number
df2['score'].loc[2]       # by index label (same thing when index is default)

np.float64(0.1)

In [15]:
data3 = {
    'player': ['Mario', 'Luigi', 'Peach', 'Bowser', 'Toad', 'Yoshi'],
    'score': [0.72, 0.45, 0.91, 0.38, 0.85, 0.63]
}

df3 = pd.DataFrame(data3)
print(df3)

   player  score
0   Mario   0.72
1   Luigi   0.45
2   Peach   0.91
3  Bowser   0.38
4    Toad   0.85
5   Yoshi   0.63


## Argsort

In [23]:
scores = np.array([0.8, 0.1, 0.95, 0.3, 0.5])

sorted_scores = np.argsort(scores)[::-1]
print(sorted_scores)
print(scores[sorted_scores])


[2 0 4 3 1]
[0.95 0.8  0.5  0.3  0.1 ]


In [25]:
movies = np.array(["Inception", "Titanic", "The Matrix", "Interstellar", "Parasite"])
print(movies[sorted_scores])

['The Matrix' 'Inception' 'Parasite' 'Interstellar' 'Titanic']


In [29]:
scores = pd.Series([0.3, 0.9, 0.1, 0.75, 0.5])
movie_titles = pd.Series(["Inception", "Titanic", "The Matrix", "Interstellar", "Parasite"])
sorted_sc = scores.argsort().values[::-1]
print(movie_titles[sorted_sc])

1         Titanic
3    Interstellar
4        Parasite
0       Inception
2      The Matrix
dtype: str


In [35]:
scores = pd.Series([0.45, 0.88, 0.23, 0.91, 0.67])
titles = pd.Series(["Alien", "Gladiator", "Frozen", "Mad Max", "Dunkirk"])

sorted_index = scores.argsort().values[::-1][:3]
print(titles[sorted_index].values)

<StringArray>
['Mad Max', 'Gladiator', 'Dunkirk']
Length: 3, dtype: str
