In [12]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
documents = [
    "the cat sat on the mat",
    "the dog sat on the log",
    "the cat chased the dog",
    "the fish swam in the sea",
    "the sea is deep and dark"
]

In [3]:
df_docs = pd.DataFrame({'text': documents})
print(df_docs)

                       text
0    the cat sat on the mat
1    the dog sat on the log
2    the cat chased the dog
3  the fish swam in the sea
4  the sea is deep and dark


In [4]:
vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix = vectorizer.fit_transform(documents)

print(tfidf_matrix.shape)

feature_names = vectorizer.get_feature_names_out()
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)
print(df_tfidf)

(5, 11)
        cat    chased      dark      deep       dog      fish       log  \
0  0.531772  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000  0.000000  0.531772  0.000000  0.659118   
2  0.531772  0.659118  0.000000  0.000000  0.531772  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.614189  0.000000   
4  0.000000  0.000000  0.614189  0.614189  0.000000  0.000000  0.000000   

        mat       sat       sea      swam  
0  0.659118  0.531772  0.000000  0.000000  
1  0.000000  0.531772  0.000000  0.000000  
2  0.000000  0.000000  0.000000  0.000000  
3  0.000000  0.000000  0.495524  0.614189  
4  0.000000  0.000000  0.495524  0.000000  


In [5]:
similarity_matrix = cosine_similarity(tfidf_matrix)
df_similarity = pd.DataFrame(similarity_matrix)
print(df_similarity)

          0         1         2         3         4
0  1.000000  0.282782  0.282782  0.000000  0.000000
1  0.282782  1.000000  0.282782  0.000000  0.000000
2  0.282782  0.282782  1.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000  1.000000  0.245544
4  0.000000  0.000000  0.000000  0.245544  1.000000


In [6]:
row = tfidf_matrix[0].toarray()
print(row)
print(row.shape)

[[0.53177225 0.         0.         0.         0.         0.
  0.         0.659118   0.53177225 0.         0.        ]]
(1, 11)


In [7]:
def get_document_vector(index):
    row = tfidf_matrix[index].toarray()
    return row

print(get_document_vector(0))
print(get_document_vector(3))

[[0.53177225 0.         0.         0.         0.         0.
  0.         0.659118   0.53177225 0.         0.        ]]
[[0.         0.         0.         0.         0.         0.61418897
  0.         0.         0.         0.49552379 0.61418897]]


In [8]:
def find_similar (index, tfidf_matrix):
    row = get_document_vector(index)
    similarity_matrix= cosine_similarity(row, tfidf_matrix)

    return similarity_matrix

print(find_similar(3,tfidf_matrix ))

[[0.         0.         0.         1.         0.24554383]]


In [11]:
match = df_docs[df_docs['text'] == "the cat sat on the mat"]

if match.empty:
    print("Title not found")
else:
    index = match.index[0]
    print(index)

0


In [14]:
scores = np.array([0.0, 0.28, 0.28, 0.0, 0.53])
sorted_scores = np.argsort(scores)[::-1]
print(sorted_scores)
top5 = sorted_scores[1:6]
print(top5)

[4 2 1 3 0]
[2 1 3 0]
